import type { Metadata } from "next";
import "./globals.css";
import Footer from "../components/UI/Footer";
import MainMenu from "../components/UI/MainMenu";
import StoreProvider from "../redux/StoreProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <StoreProvider>
                    <div id="cart-portal"></div>
                    <MainMenu />
                    {children}

                    <Footer />
                </StoreProvider>
            </body>
        </html>
    );
}
